FROM ubuntu:jammy

RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8

RUN apt-get update && apt-get install -y software-properties-common curl && \
    add-apt-repository universe
   
RUN apt install python

